// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  // zobacz czy ten komentarz będzie na github
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBi7wlez_cFo88VppW9ig7X7JLVfeMO-g',
    appId: '1:608561917913:web:32b50296e66bcfe13e33c8',
    messagingSenderId: '608561917913',
    projectId: 'inteligentny-dom-5c538',
    authDomain: 'inteligentny-dom-5c538.firebaseapp.com',
    databaseURL: 'https://inteligentny-dom-5c538-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'inteligentny-dom-5c538.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1LfWx1-K_4iyLDdJ_xeYyhkuYWeRUTqc',
    appId: '1:608561917913:android:0d3d9b0de2ee2b183e33c8',
    messagingSenderId: '608561917913',
    projectId: 'inteligentny-dom-5c538',
    databaseURL: 'https://inteligentny-dom-5c538-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'inteligentny-dom-5c538.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI_ILwT_rH3qfMFwyWWwmWALBBjhNUMxg',
    appId: '1:608561917913:ios:243a6e1fb5af046f3e33c8',
    messagingSenderId: '608561917913',
    projectId: 'inteligentny-dom-5c538',
    databaseURL: 'https://inteligentny-dom-5c538-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'inteligentny-dom-5c538.appspot.com',
    iosClientId: '608561917913-i5437v6brjb263n0ihsb04nv8mkk34rj.apps.googleusercontent.com',
    iosBundleId: 'com.stanislawszewerda.inteligentnyDom5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI_ILwT_rH3qfMFwyWWwmWALBBjhNUMxg',
    appId: '1:608561917913:ios:327f52c0984363323e33c8',
    messagingSenderId: '608561917913',
    projectId: 'inteligentny-dom-5c538',
    databaseURL: 'https://inteligentny-dom-5c538-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'inteligentny-dom-5c538.appspot.com',
    iosClientId: '608561917913-4ilal05ru4h140uuknhckc0jdshgr2lc.apps.googleusercontent.com',
    iosBundleId: 'com.stanislawszewerda.inteligentnyDom5.RunnerTests',
  );
}
